###############################
# PARAMS REQUIRED
###############################
################ NCBI (attributes)
geo_loc_name: "USA"
host: "Homo sapiens"
sample_type: "whole organism"

################ NCBI (metadata)
library_strategy: "WGS"
library_source: "Genomic"
library_selection: "Random"
library_layout: "Paired"
platform: "Illumina"
design_description: "WGS by Illumina MiSeq using Illumina DNA Prep library prep"
filetype: "fastq"

###############################
# PARAMS Optional
###############################
############# NCBI (attributes)
altitude: ""
bioproject_accession: "PRJNA288601"
biomaterial_provider: ""
collected_by: "Ohio Department of Health Laboratory"
culture_collection: ""
depth: ""
env_broad_scale: ""
genotype: ""
host_tissue_sampled: ""
identified_by: ""
lab_host: ""
lat_lon: ""
mating_type: ""
passage_history: ""
samp_size: ""
serotype: ""
serovar: ""
specimen_voucher: ""
strain: ""
temp: ""
description: ""