name: mkdocs_build_deploy
on:
  workflow_dispatch:
  push:
   branches:
    - master
    - dev
   paths:
     - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Ensure LFS files are fetched

      - name: Install MkDocs and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          git lfs pull  # Fetch all LFS files
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin pymdown-extensions

      - name: Verify LFS Files
        run: git lfs ls-files  # Debugging step to ensure LFS files are pulled

      - name: Build MkDocs Site
        run: |
          mkdocs build
          ls -l site/ || echo "MkDocs site/ directory not found"

      - name: Deploy Docs with MkDocs
        run: |
          if [ ! -d "site" ]; then
            echo "Error: MkDocs did not generate the site directory!"
            exit 1
          fi
          git checkout --orphan gh-pages
          git rm -rf .
          mv site/* .
          git add .
          git commit -m "Deploy MkDocs site"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/ODHL/ODHL_AR.git" gh-pages
