name: mkdocs_build_deploy
on:
  workflow_dispatch:
  push:
   branches:
    - master
    - dev
   paths:
     - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Fetch LFS files

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          git lfs pull  # Ensure all LFS files are downloaded

      - name: Verify LFS Files
        run: git lfs ls-files  # Debugging step to confirm LFS files exist

      - name: Build MkDocs Site
        run: |
          pip install mkdocs mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install pymdown-extensions  # Ensure emoji support

      - name: Prepare Git for LFS Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy Docs to GitHub Pages with LFS Support
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv site/* .
          git add .
          git commit -m "Deploy MkDocs site"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/ODHL/ODHL_AR.git" gh-pages
