name: mkdocs_build_deploy
on:
  workflow_dispatch:
  push:
   branches:
    - master
    - dev
   paths:
     - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          lfs: true # Ensures LFS files are fetched

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          git lfs pull

      - name: Verify LFS Files
        run: git lfs ls-files  # Debugging step to check if LFS files are present

      - name: Ensure Git LFS is Available for MkDocs
        run: |
          git config --global core.autocrlf false
          git config --global filter.lfs.process "git-lfs filter-process"
          git config --global filter.lfs.required true
          git config --global filter.lfs.smudge "git-lfs smudge --skip"
          git config --global filter.lfs.clean "git-lfs clean"

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt
